language: go
before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.74.3_Linux-64bit.deb
install: skip
branches:
  only:
    - master
    - main
script:
  - cd exampleSite && hugo --minify --themesDir ../..
